apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: busybox-http-app
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: 2018-06-12T16:11:44Z
    creationTimestamp: null
    generation: 3
    name: busybox-http-app
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/busybox/busybox-http-app:1.0
      generation: 2
      importPolicy: {}
      name: "1.0"
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/busybox/busybox-http-app:2.0
      generation: 3
      importPolicy: {}
      name: "2.0"
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/busybox/busybox-http-app:latest
      generation: 1
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: busybox-http-app
    name: busybox-http-app
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: busybox-http-app
      deploymentconfig: busybox-http-app
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: busybox-http-app
          deploymentconfig: busybox-http-app
      spec:
        containers:
        - image: docker.io/openshift/busybox-http-app@sha256:ea46cdac5f18d74b50fdef264c2e9ea46c938062369e8ca88a118b4f68594e43
          imagePullPolicy: IfNotPresent
          name: busybox-http-app
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - busybox-http-app
        from:
          kind: ImageStreamTag
          name: busybox-http-app:1.0
          namespace: busybox
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: busybox-http-app
    name: busybox-http-app
  spec:
    host: busybox-http-app-busybox.192.168.42.203.nip.io
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: busybox-http-app
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-06-12T16:16:36Z
        status: "True"
        type: Admitted
      host: busybox-http-app-busybox.192.168.42.203.nip.io
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: busybox-http-app
      openshift.io/deployment.name: busybox-http-app-1
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/scc: restricted
    creationTimestamp: null
    generateName: busybox-http-app-1-
    labels:
      app: busybox-http-app
      deployment: busybox-http-app-1
      deploymentconfig: busybox-http-app
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicationController
      name: busybox-http-app-1
      uid: 9287cf16-6e5b-11e8-80fe-ca6ddf974a86
  spec:
    containers:
    - image: docker.io/openshift/busybox-http-app@sha256:ea46cdac5f18d74b50fdef264c2e9ea46c938062369e8ca88a118b4f68594e43
      imagePullPolicy: IfNotPresent
      name: busybox-http-app
      ports:
      - containerPort: 8080
        protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          drop:
          - KILL
          - MKNOD
          - SETGID
          - SETUID
        runAsUser: 1000160000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-l558x
        readOnly: true
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: default-dockercfg-nptw9
    nodeName: localhost
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000160000
      seLinuxOptions:
        level: s0:c13,c2
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    volumes:
    - name: default-token-l558x
      secret:
        defaultMode: 420
        secretName: default-token-l558x
  status:
    phase: Pending
    qosClass: BestEffort
- apiVersion: v1
  kind: ReplicationController
  metadata:
    annotations:
      openshift.io/deployer-pod.completed-at: 2018-06-12 16:13:51 +0000 UTC
      openshift.io/deployer-pod.created-at: 2018-06-12 16:13:41 +0000 UTC
      openshift.io/deployer-pod.name: busybox-http-app-1-deploy
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: busybox-http-app
      openshift.io/deployment.phase: Complete
      openshift.io/deployment.replicas: "1"
      openshift.io/deployment.status-reason: config change
      openshift.io/encoded-deployment-config: |
        {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"busybox-http-app","namespace":"busybox","selfLink":"/apis/apps.openshift.io/v1/namespaces/busybox/deploymentconfigs/busybox-http-app","uid":"91e54ad1-6e5b-11e8-80fe-ca6ddf974a86","resourceVersion":"324045","generation":2,"creationTimestamp":"2018-06-12T16:13:40Z","labels":{"app":"busybox-http-app"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["busybox-http-app"],"from":{"kind":"ImageStreamTag","namespace":"busybox","name":"busybox-http-app:1.0"},"lastTriggeredImage":"docker.io/openshift/busybox-http-app@sha256:ea46cdac5f18d74b50fdef264c2e9ea46c938062369e8ca88a118b4f68594e43"}}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"app":"busybox-http-app","deploymentconfig":"busybox-http-app"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"busybox-http-app","deploymentconfig":"busybox-http-app"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"containers":[{"name":"busybox-http-app","image":"docker.io/openshift/busybox-http-app@sha256:ea46cdac5f18d74b50fdef264c2e9ea46c938062369e8ca88a118b4f68594e43","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":1,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2018-06-12T16:13:40Z","lastTransitionTime":"2018-06-12T16:13:40Z","message":"Deployment config does not have minimum availability."}]}}
    creationTimestamp: null
    generation: 1
    labels:
      app: busybox-http-app
      openshift.io/deployment-config.name: busybox-http-app
    name: busybox-http-app-1
    ownerReferences:
    - apiVersion: apps.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: DeploymentConfig
      name: busybox-http-app
      uid: 91e54ad1-6e5b-11e8-80fe-ca6ddf974a86
  spec:
    replicas: 1
    selector:
      app: busybox-http-app
      deployment: busybox-http-app-1
      deploymentconfig: busybox-http-app
    template:
      metadata:
        annotations:
          openshift.io/deployment-config.latest-version: "1"
          openshift.io/deployment-config.name: busybox-http-app
          openshift.io/deployment.name: busybox-http-app-1
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: busybox-http-app
          deployment: busybox-http-app-1
          deploymentconfig: busybox-http-app
      spec:
        containers:
        - image: docker.io/openshift/busybox-http-app@sha256:ea46cdac5f18d74b50fdef264c2e9ea46c938062369e8ca88a118b4f68594e43
          imagePullPolicy: IfNotPresent
          name: busybox-http-app
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    replicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: busybox-http-app
    name: busybox-http-app
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: busybox-http-app
      deploymentconfig: busybox-http-app
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
